doc(readme): fix bonita version
bonitasoft/rest-api-extension-user-information-example pull request #1
Opened 2018-12-21 09:27 UTC by tbouffard

also change the description about what to do for issues. The github issues tracker is currently unavailable.
We have to activate it or send the users to the Bonita Community forum or issues tracker

2018-12-26 09:53 UTC, amottier requested changes

2018-12-26 09:53 UTC, amottier commented on README.md
> +This example has been created and built with Bonita BPM 7.7.4 Enterprise Edition.
Good catch!

2018-12-26 09:53 UTC, amottier commented on README.md
> +Reports issues and improvement request on community forum????.
I enabled the GitHub issue tracker.

2020-06-04 13:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/rest-api-extension-user-information-example?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/rest-api-extension-user-information-example?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/rest-api-extension-user-information-example?pullRequest=1) it.</sub>

2020-06-16 07:26 UTC, tbouffard commented
Closing as the forked repo has been deleted.

2020-06-16 07:26 UTC, closed without merging